import { ApiProperty } from '@nestjs/swagger';

/** Shape returned by `POST /category/newCategory`. */
export class CategoryResponseDto {
    @ApiProperty({
        description: 'Generated by the database',
        example: 'b1c2d3e4-0000-4000-8000-000000000000',
    })
    id: string;

    @ApiProperty({
        description: 'Category title',
        example: 'programming',
    })
    title: string;

    @ApiProperty({
        description: 'Short description of the category',
        example: 'this category for programming learnings',
    })
    bio: string;

    @ApiProperty({
        description: 'Owner, taken from the access token',
        example: 'a0e0d0c0-0000-4000-8000-000000000000',
    })
    userId: string;

    @ApiProperty({ description: 'Auto-generated by the database' })
    createdAt: Date;

    @ApiProperty({ description: 'Auto-generated by the database' })
    updatedAt: Date;
}