import { ApiProperty } from '@nestjs/swagger';
import { TodoPriority, TodoStatus } from '../enums';

/** Shape returned by the to-do routes. */
export class TodoResponseDto {
    @ApiProperty({
        description: 'Generated by the database',
        example: 'c1d2e3f4-0000-4000-8000-000000000000',
    })
    id: string;

    @ApiProperty({
        description: 'Title of the task',
        example: 'Finish NestJS module',
    })
    title: string;

    @ApiProperty({
        description: 'Detailed description of the task',
        example: 'Write DTOs and configure Swagger documentation',
    })
    bio: string;

    @ApiProperty({
        description: 'Task status',
        enum: TodoStatus,
        example: TodoStatus.PENDING,
    })
    status: TodoStatus;

    @ApiProperty({
        description: 'Task priority level',
        enum: TodoPriority,
        example: TodoPriority.MEDIUM,
    })
    priority: TodoPriority;

    @ApiProperty({
        description: 'Owner, taken from the access token',
        example: 'a0e0d0c0-0000-4000-8000-000000000000',
    })
    userId: string;

    @ApiProperty({
        description: 'The category this todo belongs to',
        example: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        nullable: true,
    })
    categoryId: string | null;

    @ApiProperty({ description: 'Auto-generated by the database' })
    createdAt: Date;

    @ApiProperty({ description: 'Auto-generated by the database' })
    updatedAt: Date;
}

/** Shape returned by GET /to-do/:id. */
export class TodoByIdResponseDto {
    @ApiProperty({
        description: 'Title of the task',
        example: 'Finish NestJS module',
    })
    title: string;

    @ApiProperty({
        description: 'Task status',
        enum: TodoStatus,
        example: TodoStatus.PENDING,
    })
    status: TodoStatus;

    @ApiProperty({
        description: 'Detailed description of the task',
        example: 'Write DTOs and configure Swagger documentation',
    })
    bio: string;

    @ApiProperty({
        description: 'Task priority level',
        enum: TodoPriority,
        example: TodoPriority.MEDIUM,
    })
    priority: TodoPriority;

    @ApiProperty({
        description: 'The category this todo belongs to',
        example: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        nullable: true,
    })
    categoryId: string | null;
}

/** Shape returned by PATCH /to-do/editTodo/:id. */
export class TodoEditResponseDto {
    @ApiProperty({
        description: 'Title of the task',
        example: 'Finish NestJS module',
    })
    title: string;

    @ApiProperty({
        description: 'Detailed description of the task',
        example: 'Write DTOs and configure Swagger documentation',
    })
    bio: string;

    @ApiProperty({
        description: 'Task status',
        enum: TodoStatus,
        example: TodoStatus.PENDING,
    })
    status: TodoStatus;

    @ApiProperty({
        description: 'Task priority level',
        enum: TodoPriority,
        example: TodoPriority.MEDIUM,
    })
    priority: TodoPriority;
}

/** Shape returned by GET /to-do/category/:categoryId. */
export class TodoListResponseDto {
    @ApiProperty({
        description: 'Generated by the database',
        example: 'c1d2e3f4-0000-4000-8000-000000000000',
    })
    id: string;

    @ApiProperty({
        description: 'Title of the task',
        example: 'Finish NestJS module',
    })
    title: string;

    @ApiProperty({
        description: 'Task status',
        enum: TodoStatus,
        example: TodoStatus.PENDING,
    })
    status: TodoStatus;

    @ApiProperty({
        description: 'Detailed description of the task',
        example: 'Write DTOs and configure Swagger documentation',
    })
    bio: string;

    @ApiProperty({
        description: 'Task priority level',
        enum: TodoPriority,
        example: TodoPriority.MEDIUM,
    })
    priority: TodoPriority;
}
